# VÁRIAVEL DE AMBIENTE
@apiurl = http://localhost:3000/

# TESTANDO ENDPOINTS DOS USUÁRIOS
# 1- CRIANDO UM POST
POST {{apiurl}}Api/Posts/Create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTE4OTFlNTQwMTczYmFjMDljODMzZiIsImlhdCI6MTY3MTUzMDc4OSwiZXhwIjoxNjcxNjE3MTg5fQ.eXqbFc-A_aHdAuQsaPXB_EOAJwVaQQLOb-zegzwbNXE

{
    "title": "Nova postagem MERN",
    "text": "Mern stackk ",
    "banner": "https://www.imaginarycloud.com/blog/content/images/2022/03/VS--1-.jpg"
  }

###

# 2- LISTANDO TODAS POSTAGENS
GET {{apiurl}}Api/Posts/List HTTP/1.1

###

# 3- BUSCANDO A ULTIMA POSTAGEM
GET {{apiurl}}Api/Posts/Top HTTP/1.1

###

# 4- BUSCANDO POST POR ID
GET {{apiurl}}Api/Posts/63a195cd386591fbb13bdf51 HTTP/1.1

###
# 4- BUSCANDO POST PELO TITULO
GET {{apiurl}}Api/Posts/Search?title=Django HTTP/1.1