# VÁRIAVEL DE AMBIENTE
@apiurl = http://localhost:3000/

# TESTANDO ENDPOINTS DE AUTHENTICAÇÃO DO USUÁRIO
# 1- LOGANDO USUARIO
POST {{apiurl}}Api/Users/Auth/Login HTTP/1.1
content-type: application/json

{
    "email": "zezao@gmail.com",
    "password": "131288Brn@"
}

