# VÁRIAVEL DE AMBIENTE
@apiurl = http://localhost:3000/

# TESTANDO ENDPOINTS DOS USUÁRIOS
POST {{apiurl}}Api/Users/Register HTTP/1.1
content-type: application/json

{
    "name": "Richard Alves Correia",
    "username": "RichardAlz",
    "email": "Richard@gmail.com",
    "password": "131288Brn@",
    "profileImage": "https://avatars.githubusercontent.com/u/58440875?v=4",
    "backgroundImage": "https://www.imaginarycloud.com/blog/content/images/2022/03/VS--1-.jpg",
    "about": "Jogador de FriFAS!"
  }

###

# Testando a Listagem de usuários
GET {{apiurl}}Api/Users/List HTTP/1.1