# VÁRIAVEL DE AMBIENTE
@apiurl = http://localhost:3000/

# TESTANDO ENDPOINTS DOS USUÁRIOS
# 1- CRIANDO USUARIO
POST {{apiurl}}Api/Users/Register HTTP/1.1
content-type: application/json

{
    "name": "Richard Alves Correia",
    "username": "RichardAlz",
    "email": "Richard@gmail.com",
    "password": "131288Brn@",
    "profileImage": "https://avatars.githubusercontent.com/u/58440875?v=4",
    "backgroundImage": "https://www.imaginarycloud.com/blog/content/images/2022/03/VS--1-.jpg",
    "about": "Jogador de FriFAS!"
  }

RESPONSE: HTTP/1.1 200 OK

###

# 2- LISTANDO USUÀRIOS CRIADOS
GET {{apiurl}}Api/Users/List HTTP/1.1
RESPONSE: HTTP/1.1 200 OK

###

# 3- BUSCANDO USUÁRIO POR ID
GET {{apiurl}}Api/Users/639d2a7387e3c9bddcef459c HTTP/1.1
RESPONSE: HTTP/1.1 200 OK

###

# 4- ATUALIZANDO USUÁRIOS
PATCH {{apiurl}}Api/Users/Atualizar/639d2a7387e3c9bddcef459c HTTP/1.1
content-type: application/json

{
    "name": "Richard Alves Correia",
    "username": "RichardAlz",
    "email": "Richard@gmail.com",
    "password": "131288Brn@",
    "profileImage": "https://avatars.githubusercontent.com/u/58440875?v=4",
    "backgroundImage": "https://www.imaginarycloud.com/blog/content/images/2022/03/VS--1-.jpg",
    "about": "Jogador de FriFAS!!"
  }

RESPONSE: HTTP/1.1 200 OK

###

